### PR TITLE
Add example for sampling across timesteps

### LINKED ISSUE #54: Example for Sampling of PLUTO data
Sampling of PLUTO data now works.  Having an example and/or some explanation on how to do this. The emphasis in the example should be on having multiple time steps in the data structure (basically this does not even have to be PLUTO data the same will be done with MAS data with multiple time steps).

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/predsci/PsiPy/issues/54. @mbennun or @thepeteriley could you review the new example I've added, and let me know if anything doesn't make sense or if you have any suggestions for improvements?

### CODE REVIEW

**Comment by mbennun** [comment]
I tested the example and it works correctly.  I am not sure  that sampling in-between MAS (or PLUTO) dumps is that important, Pete should comment on that.  It would be useful to provide a line of code showing how to create a time series plot at either fixed or not r, theta, phi, for all the dumps.  The x-axis needs the time units. The y-axis label and the title are very clear.

**Comment by thepeteriley** [comment]
Agreed, atm, probably not necessary to interpolate between time steps.

**Comment by dstansby** [comment]
Thanks for the feedback - I think it makes sense to use `.sample_at_coords()` to do this because it lets you choose a longitude/latitude/radius coordinate in units instead of choosing one of the array indices of the model. So I've just modified the example I had wrote to use the two time coordinates loaded in the model.

Is this what you were after?

For time units, I'm not sure what they are - currently they're just stored as integers, do you know what values and/or units they should be?

**Comment by mbennun** [comment]
Yes I think this makes sense.  The time of actual dumps have to be retrieved from the history file of the runs.  This is not simple I can provide some bash scripts that do that

**Pull request merged**
